# Generated by Django 6.1.1 on 2026-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_certificaterequest_certifacate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Комментарий ответсвенного сотрудника', max_length=255),
        ),
    ]
