# Generated by Django 6.1.1 on 2026-09-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifacate_type', models.CharField(help_text='Тип справки (2-НДФЛ, с места работы и др.)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Комментарий сотрудника (период, цель и пр.)')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('ready', 'Готов'), ('rejected', 'Отклонен')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
