# Generated by Django 6.1.1 on 2026-09-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_certificaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='user',
            field=models.ForeignKey(choices=[('income', 'О доходах'), ('employment', 'С места работы'), ('vacation', 'Об использованных отпусках'), ('other', 'Прочее')], on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
