# Generated by Django 6.1.1 on 2026-09-23 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_certificaterequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='certifacate_type',
            field=models.CharField(choices=[('income', 'О доходах'), ('employment', 'С места работы'), ('vacation', 'Об использованных отпусках'), ('other', 'Прочее')], help_text='Тип справки (2-НДФЛ, с места работы и др.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
