# Generated by Django 6.1.1 on 2026-09-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_certificaterequest_admin_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='certifacate_type',
            new_name='certificate_type',
        ),
    ]
