# Generated by Django 6.1.1 on 2026-09-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_rename_certifacate_type_certificaterequest_certificate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificaterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на справку', 'verbose_name_plural': 'Заявки на справки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Комментарий ответсвенного сотрудника', max_length=255, verbose_name='Комментарий ответственного'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('income', 'О доходах'), ('employment', 'С места работы'), ('vacation', 'Об использованных отпусках'), ('other', 'Прочее')], help_text='Тип справки (2-НДФЛ, с места работы и др.)', max_length=50, verbose_name='Тип справки'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='description',
            field=models.TextField(blank=True, help_text='Комментарий сотрудника (период, цель и пр.)', verbose_name='Комментарий сотрудника'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('ready', 'Готов'), ('rejected', 'Отклонен')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
